-- ============================================================
-- STUDENT MANAGEMENT SYSTEM - DATABASE SETUP
-- ============================================================
-- Run this file using:
--   psql -U postgres -f database.sql
-- or open psql shell and paste the contents in order.
-- ============================================================

-- ------------------------------------------------------------
-- 1. CREATE DATABASE
-- ------------------------------------------------------------
-- NOTE: You cannot run CREATE DATABASE inside a transaction block
-- or inside a script that also creates tables in the same connection
-- in some psql configurations. Run this line first, on its own,
-- then reconnect to the new database before running the rest.

CREATE DATABASE student_management;

-- After running the line above, connect to the new database:
--   \c student_management
-- Then run everything below.

-- ------------------------------------------------------------
-- 2. EXTENSIONS
-- ------------------------------------------------------------
-- pgcrypto is used later if we ever need gen_random_uuid().
-- Not strictly required for this schema, but useful to have.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ------------------------------------------------------------
-- 3. TABLE: students
-- ------------------------------------------------------------
-- admission_number is generated by the BACKEND (Node.js), not
-- by the database, so that we have full control over the
-- ADM000001 style formatting and can keep business logic in
-- one place (the Node app), not split between DB and app.
--
-- We still enforce UNIQUE at the DB level as a safety net.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS students (
    id                SERIAL PRIMARY KEY,
    admission_number  VARCHAR(20)  NOT NULL UNIQUE,
    name              VARCHAR(100) NOT NULL,
    course            VARCHAR(100) NOT NULL,
    year              INTEGER      NOT NULL CHECK (year BETWEEN 1 AND 6),
    date_of_birth     DATE         NOT NULL,
    email             VARCHAR(150) NOT NULL UNIQUE,
    mobile_number     VARCHAR(15)  NOT NULL,
    gender            VARCHAR(10)  NOT NULL CHECK (gender IN ('Male', 'Female', 'Other')),
    address           TEXT         NOT NULL,
    photo_url         VARCHAR(255),
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 4. TABLE: activity_logs  (Bonus Feature)
-- ------------------------------------------------------------
-- Tracks every CREATE / UPDATE / DELETE action performed on a
-- student record. student_id is nullable + ON DELETE SET NULL
-- so that deleting a student does not wipe out the audit trail
-- of the deletion itself.
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS activity_logs (
    id            SERIAL PRIMARY KEY,
    student_id    INTEGER REFERENCES students(id) ON DELETE SET NULL,
    action        VARCHAR(20) NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
    description   TEXT NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ------------------------------------------------------------
-- 5. INDEXES
-- ------------------------------------------------------------
-- These speed up the exact operations our API needs:
-- search by name, search/filter by course, sort by year,
-- and lookups by admission number.
-- ------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_students_name              ON students (name);
CREATE INDEX IF NOT EXISTS idx_students_admission_number   ON students (admission_number);
CREATE INDEX IF NOT EXISTS idx_students_course             ON students (course);
CREATE INDEX IF NOT EXISTS idx_students_year               ON students (year);
CREATE INDEX IF NOT EXISTS idx_activity_logs_student_id     ON activity_logs (student_id);

-- ------------------------------------------------------------
-- 6. AUTO-UPDATE updated_at TRIGGER
-- ------------------------------------------------------------
-- Whenever a student row is updated, updated_at is refreshed
-- automatically, so the backend never has to remember to set it.
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_students_updated_at ON students;

CREATE TRIGGER trg_students_updated_at
BEFORE UPDATE ON students
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
-- 7. SEED DATA (Optional)
-- ------------------------------------------------------------
-- A handful of sample students so the dashboard is not empty
-- the first time you run the app.
-- ------------------------------------------------------------

INSERT INTO students
    (admission_number, name, course, year, date_of_birth, email, mobile_number, gender, address, photo_url)
VALUES
    ('ADM000001', 'Aarav Sharma',  'Computer Science', 2, '2004-05-12', 'aarav.sharma@example.com',  '9876543210', 'Male',   '12 MG Road, Pune, Maharashtra',        NULL),
    ('ADM000002', 'Priya Nair',    'Electronics',      1, '2005-08-23', 'priya.nair@example.com',    '9876543211', 'Female', '45 Marine Drive, Mumbai, Maharashtra', NULL),
    ('ADM000003', 'Rohan Mehta',   'Mechanical',        3, '2003-01-30', 'rohan.mehta@example.com',   '9876543212', 'Male',   '78 Church Street, Bengaluru, KA',       NULL),
    ('ADM000004', 'Sneha Iyer',    'Computer Science', 4, '2002-11-09', 'sneha.iyer@example.com',    '9876543213', 'Female', '23 Anna Salai, Chennai, TN',            NULL),
    ('ADM000005', 'Karan Verma',   'Civil',             2, '2004-03-17', 'karan.verma@example.com',   '9876543214', 'Male',   '9 Sector 15, Chandigarh',               NULL)
ON CONFLICT (admission_number) DO NOTHING;

-- ------------------------------------------------------------
-- 8. VERIFY
-- ------------------------------------------------------------
-- Run these manually after the script to confirm setup:
--   SELECT * FROM students;
--   SELECT * FROM activity_logs;
--   \d students
-- ------------------------------------------------------------
